# Dockerfile.generator

# Stripe event generator service
FROM trstream-base
WORKDIR /app

# Copy toml and lock and install dependencies
COPY pyproject.toml uv.lock ./
RUN uv sync --locked --no-dev --extra stripe-generator --active

# Copy source code
RUN mkdir -p src 
COPY src/integrations/stripe/generator ./src/generator
COPY src/integrations/stripe/stripe.env ./src/stripe.env

# Python path
ENV PYTHONPATH=/app/src

# entrypoint
CMD ["python", "-m", "generator.main"]