{
 "title": "Pipeline Stats - Faker",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Transaction Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(transactions_sent_total[1m]))",
     "legendFormat": "Overall"
    },
    {
     "expr": "sum by (producer) (rate(transactions_sent_total[1m]))",
     "legendFormat": "{{producer}}"
    }
   ]
  },
  {
   "title": "Total Transactions",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "round(sum(increase(transactions_sent_total[1m])))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Consumer Throguhput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(messages_consumed_total[1m]))",
     "legendFormat": "Overall"
    },
    {
     "expr": "sum by (consumer) (rate(messages_consumed_total[1m]))",
     "legendFormat": "{{consumer}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "producer_errors_total", "legendFormat": "Producers" },
    { "expr": "consumer_errors_total", "legendFormat": "Consumers" }
   ]
  }
 ]
}