# Dockerfile.partitioner

# Raw data partitioner service 
FROM trstream-base
WORKDIR /app

# Copy toml and lock and install dependencies
COPY pyproject.toml uv.lock ./
RUN uv sync --locked --no-dev --active

# Copy source code
RUN mkdir -p src 
COPY src/partitioner ./src/partitioner

# Python path
ENV PYTHONPATH=/app/src

# entrypoint
CMD ["python", "-m", "partitioner.main"]