# Dockerfile.consumer

# Kafka Consumer service
FROM trstream-base
WORKDIR /app

# Copy toml and lock and install dependencies
COPY pyproject.toml uv.lock ./
RUN uv sync --locked --no-dev --extra consumer --active

# Copy source code
RUN mkdir -p src 
COPY src/consumer ./src/consumer

# entrypoint
CMD ["python", "src/consumer/main.py"]