FROM trstream-base
WORKDIR /app

COPY pyproject.toml uv.lock ./

RUN uv sync --locked --no-dev --extra streamlit --active

RUN mkdir -p src 
COPY src/streamlit ./src/streamlit

ENV PYTHONPATH=/app

CMD ["streamlit", "run", "src/streamlit/app.py", "--server.port=8501", "--server.headless=true"]