FROM trstream-base
WORKDIR /app

COPY pyproject.toml uv.lock ./

RUN uv sync --locked --no-dev --extra producer --active

RUN mkdir -p src 
COPY src/producer ./src/producer

CMD ["python", "src/producer/producer.py"]