FROM trstream-base
WORKDIR /app

COPY pyproject.toml uv.lock ./

RUN uv sync --locked --no-dev --active

RUN mkdir -p src 
COPY src/compacter ./src/compacter

CMD ["python", "src/compacter/compacter.py"]